name: Build Release

on:
  push:
    branches: [ dev ]

jobs:

  build-release:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: build for chrome
        run: |
          npm run build-chrome
      - name: zip build artifact
        run: |
          zip -r build build
      - name: upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: chrome
          path: build.zip