name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:

    runs-on: ubuntu-20.04
    needs: [build-release]

    steps:
      - uses: actions/checkout@v1
      - name: create release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: download artifacts
        uses: actions/download-artifact@v1
        with:
          name: uploads
      - name: upload release
        id: upload-release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uploads/build.zip
          asset_name: build.zip
          asset_content_type: application/zip

  build-release:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm test
      - name: npm run build
        run: |
          npm run build
      - name: zip build artifact
        run: |
          zip -r build out
      - name: upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: uploads
          path: build.zip